name: "Munus Private Job Execution"
description: "Run a local Calimero app to process job tasks with verifiable attestation"

# Clean states between runs (optional)
nuke_on_start: false
nuke_on_end: false

# Enable auth service for protected JSON-RPC (optional)
auth_service: false

# Log level: trace, debug, info, warn, error
log_level: "info"

# Force pull latest Docker images
force_pull_image: false

# Node configuration
nodes:
  count: 1
  prefix: "munus-node"
  base_port: 2428
  base_rpc_port: 2528
  chain_id: "munus-testnet"

# Workflow steps
steps:
  # Wait for node startup
  - name: Wait for startup
    type: wait
    seconds: 3

  # Install REAL WASM application
  - name: Install Application
    type: install_application
    node: "munus-node-1"
    path: "./apps/job_processor.wasm"
    dev: true
    outputs:
      applicationId: "app_id"

  # Create execution context
  - name: Create Context
    type: create_context
    node: "munus-node-1"
    application_id: "{{app_id}}"
    outputs:
      contextId: "ctx_id"
      memberPublicKey: "member_key"

  # Execute job processing
  - name: Process Job
    type: call
    node: "munus-node-1"
    context_id: "{{ctx_id}}"
    executor_public_key: "{{member_key}}"
    method: "process_job"
    args:
      job_id: "{{JOB_ID}}"
      input_cid: "{{RESOURCE_CID}}"
      task_type: "{{TASK_TYPE}}"
      worker_address: "{{WORKER_ADDRESS}}"
    outputs:
      result: output

  # Generate signed attestation (REAL Ed25519)
  - name: Sign Attestation
    type: call
    node: "munus-node-1"
    context_id: "{{ctx_id}}"
    executor_public_key: "{{member_key}}"
    method: "sign_attestation"
    args:
      job_id: "{{JOB_ID}}"
      input_hash: "{{result.inputHash}}"
      output_hash: "{{result.outputHash}}"
      timestamp: "{{result.timestamp}}"
      worker_address: "{{WORKER_ADDRESS}}"
    outputs:
      attestation: output

  # Save artifacts locally
  - name: Save Outputs
    type: script
    target: local
    inline: |
      echo '{{result}}' > outputs.json
      echo '{{attestation}}' > attestation.json
      echo "✅ Job outputs saved to outputs.json"
      echo "✅ Attestation saved to attestation.json"
      echo "📝 Output hash: {{result.output_hash}}"
      echo "🔑 Signature: {{attestation.signature}}"

  # Optional: Verify attestation
  - name: Verify Attestation
    type: script
    target: local
    inline: |
      node ../verify/verify-attestation.js attestation.json outputs.json
      echo "✅ Attestation verified successfully"

